apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-web-front
  labels:
    app: angular-web-front
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-web-front
      tier: frontend
  strategy:
    # All existing Pods are killed before new ones are created
    type: Recreate
    # Template for the Pods in this deployment
  template:
    metadata:
      labels:
        app: angular-web-front
        tier: frontend
    spec:
      containers:
        - name: angular-web-front
          image: yurui113/angular-web-front:latest
          imagePullPolicy: "Always"
          #imagePullPolicy: "IfNotPresent"
          ports:
            # The port that the container exposes
            - containerPort: 80
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"          
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10