apiVersion: v1
kind: Service
metadata:
  name: angular-web-front
  labels:
    app: angular-web-front
    tier: frontend
spec:
  selector:
    app: angular-web-front
    tier: frontend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
