apiVersion: v1
# Create a PersistentVolumeClaim to request a PersistentVolume storage
kind: PersistentVolumeClaim
metadata:
  name: postgres
  labels:
    app: postgres
    tier: database
spec:
  # Request a certain storage class
  storageClassName: taylor-local-storage
  accessModes:
    # the volume can be mounted as read-write by a single node.
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
