apiVersion: v1
kind: Secret
metadata:
  name: postgres
# Opaque is the default Secret type
type: Opaque
data:
  # Below data are encoded by base64
  POSTGRES_PASSWORD: c2VjcmV0
stringData:
  # If you do not want to perform the base64 encoding,
  # you can choose to use the stringData field instead.
  POSTGRES_USER: taylor
