corsOrigin: http://20.6.154.6
spring:
  datasource:
    url: jdbc:postgresql://bookrestapi-server.postgres.database.azure.com/bookrestapi-database
    username: zolmumdaph
    password: 683Z7OJR7EQBQ60U$
    sslmode: require
  jpa:
    show-sql: false
server:
  port: 80