corsOrigin: ${API_CLIENTS:#{'http://localhost:4200'}}
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB:book_database}
    #url: jdbc:postgresql://postgres-service:5432/book_database
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 80
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true