apiVersion: v1
kind: Service
metadata:
  name: rest-api
  labels:
    app: rest-api
    tier: backend
spec:
  selector:
    app: rest-api
    tier: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
